NOTES_OFFSET = {
    'bong': 64,
    '🔔': 88,
    '🚫': 48,
    '🤬': 83,
    'buzzer': 46,
    'airhorn': 51,
    '🎹': 66,
    'robtopphone': 66,
    '🎸': 42,
    'hoenn': 66,
    '🎺': 66,
    'obama': 66,
    'samurai': 69,
    'familyguy': 72,
    'ultrainstinct': 69,
    'morshu': 56,
    'bup': 69,
    'mariopaint_mario': 66,
    'mariopaint_luigi': 66,
    'mariopaint_star': 78,
    'mariopaint_flower': 66,
    'mariopaint_gameboy': 66,
    'mariopaint_dog': 65,
    'mariopaint_cat': 65,
    'mariopaint_swan': 66,
    'mariopaint_baby': 73,
    'mariopaint_plane': 66,
    'mariopaint_car': 66,
    'tab_sounds': 96,
    'choruskid': 66,
    'builttoscale': 72,
    'fnf_left': 66,
    'fnf_down': 52,
    'fnf_up': 66,
    'fnf_right': 66,
    'gd_quit': 69,
    'bwomp': 54,
    '🦴': 50,
    'YOU': 73,
    'terraria_guitar': 64,
    'terraria_axe': 48,
    'amogus_emergency': 58,
    'amongdrip': 48,
    'minecraft_bell': 54,
    'noteblock_harp': 66,
    'noteblock_bass': 42,
    'noteblock_bell': 78,
    'noteblock_banjo': 66,
    'noteblock_bit': 66,
    'noteblock_chime': 78,
    'noteblock_xylophone': 78,
    'noteblock_guitar': 54,
    'noteblock_flute': 78,
    'noteblock_pling': 66
}
DRUM_NOTES = {
    35: 'adofaikick',
    36: 'adofaikick',
    37: 'sidestick',
    38: 'noteblock_snare',
    39: 'rdclap',
    40: 'hammer',
    41: 'taiko_don',
    42: 'noteblock_click',
    43: 'taiko_don',
    44: 'noteblock_click',
    45: 'taiko_don',
    46: 'ride2',
    47: '🪘',
    48: '🪘',
    49: 'ride2',
    50: '🪘',
    51: 'ride2',
    52: 'ride2',
    53: 'ride2',
    54: 'shaker',
    55: 'ride2',
    56: 'cowbell',
    57: 'ride2',
    58: 'skipshot',
    59: 'ride2',
    69: 'shaker',
    70: 'shaker',
    82: 'shaker'
}
MINECRAFT1_SETUP = {
    (0, 54): 'noteblock_bass',
    'default': 'noteblock_harp'
}
ICONS = {
    'Silence': 'icons/empty.png', 'Vine Boom': 'icons/boom.png', 'Bruh Sound Effect #2': 'icons/bruh.png',
    'Bong': 'icons/bong.png', 'Skeleton': 'icons/1f480.svg', 'Reverb Clap': 'icons/1f44f.svg',
    'what the dog doin': 'icons/1f436.svg', 'Cave Noise': 'icons/1f47d.svg', 'Bell': 'icons/minecraft_bell.png',
    'Boink': 'icons/1f4a2.svg', 'Reverb Fart': 'icons/1f4a8.svg', 'Error': 'icons/1f6ab.svg',
    'Kaching': 'icons/1f4b0.svg', 'Bonk': 'icons/1f3cf.svg', 'Bleep': 'icons/1f92c.svg', 'Alarm': 'icons/1f6a8.svg',
    'Incorrect Buzzer': 'icons/buzzer.png', 'aah': 'icons/1f170.svg', 'E': 'icons/e.png', '8': 'icons/eight.png',
    'ayo the pizza here': 'icons/1f355.svg', 'Pufferfish Augh': 'icons/1f421.svg', 'Quack': 'icons/1f986.svg',
    'Honk': 'icons/1f9a2.svg', 'Skyline Notification': 'icons/1f4f2.svg', 'Morning Flower': 'icons/1f304.svg',
    'Hitmarker': 'icons/hitmarker.png', 'Noice Click': 'icons/1f44c.svg', 'Slap': 'icons/1f590.svg',
    'Mr. Krabs Walking': 'icons/1f980.svg', 'wowowowow': 'icons/1f6ac.svg',
    'Whistle Notification': 'icons/whatsapp.png', 'Suspense': 'icons/1f631.svg', 'Alert': 'icons/2757.svg',
    'Slip': 'icons/slip.png', 'Explosion': 'icons/minecraft_explosion.png', 'Tada': 'icons/1f389.svg',
    'Frying Pan': 'icons/pan.png', 'Record Scratch': 'icons/1f4bf.svg', 'Airhorn': 'icons/airhorn.png',
    'Don': 'icons/taiko_don.png', 'Ka': 'icons/taiko_ka.png', 'Synth': 'icons/1f3b9.svg',
    'Xylophone': 'icons/robtopphone.png', 'Waterphone': 'icons/1f3bb.svg', 'Slap Bass': 'icons/1f3b8.svg',
    'Hoenn Trumpet': 'icons/hoenn.png', 'ZUNpet': 'icons/1f3ba.svg', 'Gun Reload': 'icons/gun.png',
    'Dodgeball': 'icons/dodgeball.png', 'Whip Crack': 'icons/whipcrack.png', 'Gnome': 'icons/gnome.png',
    'nope.avi': 'icons/nope.png', 'MR BEAST': 'icons/mrbeast.png', 'BARACK OBAMA': 'icons/obama.png',
    'op': 'icons/op.png', 'SLAM!': 'icons/SLAM.png', 'Ding': 'icons/stopposting.png', '21': 'icons/21.png',
    'dog dancing we no speak americano': 'icons/americano.png', 'Oof': 'icons/oof.png',
    'Subaluwa': 'icons/subaluwa.png', 'Neco-Arc': 'icons/necoarc.png', 'Samurai Techno': 'icons/samurai.png',
    'Frog': 'icons/flipnote.png', 'Family Guy Intro': 'icons/familyguy.png', 'PINGAS': 'icons/pingas.png',
    'Lego Yoda Death': 'icons/yoda.png', 'HE HE HE HAW': 'icons/hehehehaw.png',
    'Ultra Instinct': 'icons/ultrainstinct.png', 'GRAND DAD': 'icons/granddad.png',
    'Morshu MMMMMMM': 'icons/morshu.png', 'Coin': 'icons/smw_coin.png', '1-Up': 'icons/smw_1up.png',
    'Spin Jump': 'icons/smw_spinjump.png', 'Stomp': 'icons/smw_stomp2.png', 'Kick': 'icons/adofaikick.png',
    'Boss Stomp': 'icons/smw_stomp.png', 'Long Jump': 'icons/yahoo.png', 'Damage': 'icons/isaac_hurt.png',
    'Thwomp': 'icons/thwomp.png', 'Bup': 'icons/bup.png', 'Painting': 'icons/sm64_painting.png',
    'Scream': 'icons/smm_scream.png', 'Mario': 'icons/mariopaint_mario.png', 'Steel Drum': 'icons/mariopaint_luigi.png',
    'Yoshi': 'icons/smw_yoshi.png', 'Star': 'icons/mariopaint_star.png', 'Flower': 'icons/mariopaint_flower.png',
    'Gameboy': 'icons/mariopaint_gameboy.png', 'Dog': 'icons/mariopaint_dog.png', 'Cat': 'icons/mariopaint_cat.png',
    'Swan': 'icons/mariopaint_swan.png', 'Baby': 'icons/mariopaint_baby.png', 'Plane': 'icons/mariopaint_plane.png',
    'Car': 'icons/mariopaint_car.png', 'Shaker': 'icons/shaker.png', 'Hammer': 'icons/hammer.png',
    'Tom Drum': 'icons/1fa98.svg', 'Sidestick': 'icons/sidestick.png', 'Ride': 'icons/ride2.png',
    'Pop': 'icons/buttonpop.png', 'Skipshot': 'icons/skipshot.png', 'Otto - Enabled': 'icons/otto_on.png',
    'Otto - Disabled': 'icons/otto_off.png', 'Otto - Happy': 'icons/otto_happy.png',
    'Otto - Stressed': 'icons/otto_stress.png', 'Sounds Tab': 'icons/tab_sounds.png', 'Rows Tab': 'icons/tab_rows.png',
    'Actions Tab': 'icons/tab_actions.png', 'Decorations Tab': 'icons/tab_decorations.png',
    'Rooms Tab': 'icons/tab_rooms.png', 'Pre-echo Clap': 'icons/preecho.png', 'Tonk': 'icons/tonk.png',
    'Clap Hit': 'icons/rdclap.png', 'Mistake': 'icons/rdmistake.png', 'Midspin Clack': 'icons/midspin.png',
    'Fire Midspin': 'icons/adofai_fire.png', 'Ice Midspin': 'icons/adofai_ice.png',
    'Level Complete': 'icons/adofaicymbal.png', 'Cowbell': 'icons/cowbell.png',
    'Karate Man - Toss': 'icons/karateman_throw.png', 'Karate Man - Offbeat Toss': 'icons/karateman_offbeat.png',
    'Karate Man - Hit': 'icons/karateman_hit.png', 'Karate Man - Bulb': 'icons/karateman_bulb.png',
    'Ook': 'icons/ook.png', 'Chorus Kid': 'icons/choruskid.png', 'Widget': 'icons/builttoscale.png',
    'Perfect Failed': 'icons/perfectfail.png', 'Skill Star': 'icons/1f31f.svg', 'Left': 'icons/fnf_left.png',
    'Down': 'icons/fnf_down.png', 'Up': 'icons/fnf_up.png', 'Right': 'icons/fnf_right.png',
    'Fail': 'icons/fnf_death.png', 'Crash': 'icons/gdcrash.png', 'Crash + Orbs': 'icons/gdcrash_orbs.png',
    'Secret Coin': 'icons/gd_coin.png', 'Mana Orbs': 'icons/gd_orbs.png', 'Diamond': 'icons/gd_diamonds.png',
    'Quit': 'icons/gd_quit.png', 'Blast Processing': 'icons/bwomp.png', 'Game Over': 'icons/undertale_crack.png',
    'sans': 'icons/sans_voice.png', 'Megalovania': 'icons/megalovania.png', 'Megalovania Note': 'icons/1f9b4.svg',
    'Encounter': 'icons/undertale_encounter.png', 'Bark': 'icons/toby.png', 'Vanish': 'icons/gaster.png',
    'Lancer Splat': 'icons/lancersplat.png', 'Death': 'icons/celeste_death.png',
    'Holy Mantle': 'icons/isaac_mantle.png', 'MOVE': 'icons/BABA.png', 'RULE': 'icons/YOU.png',
    'DEFEAT': 'icons/DEFEAT.png', 'Flip': 'icons/vvvvvv_flip.png', 'Sad': 'icons/vvvvvv_hurt.png',
    'Checkpoint': 'icons/vvvvvv_checkpoint.png', 'Flash': 'icons/vvvvvv_flash.png', 'Magic': 'icons/terraria_star.png',
    'Shatter': 'icons/terraria_pot.png', 'Reforge': 'icons/terraria_reforge.png',
    'Stellar Tune': 'icons/terraria_guitar.png', 'The Axe': 'icons/terraria_axe.png', 'Dash': 'icons/celeste_dash.png',
    'Spring': 'icons/celeste_spring.png', 'Dash Gem': 'icons/celeste_diamond.png',
    'Emergency Meeting': 'icons/amogus_emergency.png', 'Kill': 'icons/amogus_kill.png', 'AMONG US': 'icons/amongus.png',
    'Among Drip': 'icons/amongdrip.png', 'Amogus': 'icons/amogus.png', 'Anvil': 'icons/minecraft_anvil.png',
    'Note Block - Harp': 'icons/noteblock_harp.png', 'Note Block - Bass': 'icons/noteblock_bass.png',
    'Note Block - Snare': 'icons/noteblock_snare.png', 'Note Block - Hat': 'icons/noteblock_click.png',
    'Note Block - Bell': 'icons/noteblock_bell.png', 'Note Block - Banjo': 'icons/noteblock_banjo.png',
    'Note Block - Bit': 'icons/noteblock_bit.png', 'Note Block - Chime': 'icons/noteblock_chime.png',
    'Note Block - Xylophone': 'icons/noteblock_xylophone.png', 'Note Block - Guitar': 'icons/noteblock_guitar.png',
    'Note Block - Flute': 'icons/noteblock_flute.png', 'Note Block - Pling': 'icons/noteblock_pling.png'
}
SOUNDS = {
    'Silence': '_pause', 'Vine Boom': 'boom', 'Bruh Sound Effect #2': 'bruh', 'Bong': 'bong', 'Skeleton': '💀',
    'Reverb Clap': '👏', 'what the dog doin': '🐶', 'Cave Noise': '👽', 'Bell': 'minecraft_bell', 'Boink': '💢',
    'Reverb Fart': '💨', 'Error': '🚫', 'Kaching': '💰', 'Bonk': '🏏', 'Bleep': '🤬', 'Alarm': '🚨',
    'Incorrect Buzzer': 'buzzer', 'aah': '🅰', 'E': 'e', '8': 'eight', 'ayo the pizza here': '🍕',
    'Pufferfish Augh': '🐡', 'Quack': '🦆', 'Honk': '🦢', 'Skyline Notification': '📲', 'Morning Flower': '🌄',
    'Hitmarker': 'hitmarker', 'Noice Click': '👌', 'Slap': '🖐', 'Mr. Krabs Walking': '🦀', 'wowowowow': '🚬',
    'Whistle Notification': 'whatsapp', 'Suspense': '😱', 'Alert': '❗', 'Slip': 'slip',
    'Explosion': 'minecraft_explosion', 'Tada': '🎉', 'Frying Pan': 'pan', 'Record Scratch': '💿', 'Airhorn': 'airhorn',
    'Don': 'taiko_don', 'Ka': 'taiko_ka', 'Synth': '🎹', 'Xylophone': 'robtopphone', 'Waterphone': '🎻',
    'Slap Bass': '🎸', 'Hoenn Trumpet': 'hoenn', 'ZUNpet': '🎺', 'Gun Reload': 'gun', 'Dodgeball': 'dodgeball',
    'Whip Crack': 'whipcrack', 'Gnome': 'gnome', 'nope.avi': 'nope', 'MR BEAST': 'mrbeast', 'BARACK OBAMA': 'obama',
    'op': 'op', 'SLAM!': 'SLAM', 'Ding': 'stopposting', '21': '21', 'dog dancing we no speak americano': 'americano',
    'Oof': 'oof', 'Subaluwa': 'subaluwa', 'Neco-Arc': 'necoarc', 'Samurai Techno': 'samurai', 'Frog': 'flipnote',
    'Family Guy Intro': 'familyguy', 'PINGAS': 'pingas', 'Lego Yoda Death': 'yoda', 'HE HE HE HAW': 'hehehehaw',
    'Ultra Instinct': 'ultrainstinct', 'GRAND DAD': 'granddad', 'Morshu MMMMMMM': 'morshu', 'Coin': 'smw_coin',
    '1-Up': 'smw_1up', 'Spin Jump': 'smw_spinjump', 'Stomp': 'smw_stomp2', 'Kick': 'adofaikick',
    'Boss Stomp': 'smw_stomp', 'Long Jump': 'yahoo', 'Damage': 'isaac_hurt', 'Thwomp': 'thwomp', 'Bup': 'bup',
    'Painting': 'sm64_painting', 'Scream': 'smm_scream', 'Mario': 'mariopaint_mario', 'Steel Drum': 'mariopaint_luigi',
    'Yoshi': 'smw_yoshi', 'Star': 'mariopaint_star', 'Flower': 'mariopaint_flower', 'Gameboy': 'mariopaint_gameboy',
    'Dog': 'mariopaint_dog', 'Cat': 'mariopaint_cat', 'Swan': 'mariopaint_swan', 'Baby': 'mariopaint_baby',
    'Plane': 'mariopaint_plane', 'Car': 'mariopaint_car', 'Shaker': 'shaker', 'Hammer': 'hammer', 'Tom Drum': '🪘',
    'Sidestick': 'sidestick', 'Ride': 'ride2', 'Pop': 'buttonpop', 'Skipshot': 'skipshot', 'Otto - Enabled': 'otto_on',
    'Otto - Disabled': 'otto_off', 'Otto - Happy': 'otto_happy', 'Otto - Stressed': 'otto_stress',
    'Sounds Tab': 'tab_sounds', 'Rows Tab': 'tab_rows', 'Actions Tab': 'tab_actions',
    'Decorations Tab': 'tab_decorations', 'Rooms Tab': 'tab_rooms', 'Pre-echo Clap': 'preecho', 'Tonk': 'tonk',
    'Clap Hit': 'rdclap', 'Mistake': 'rdmistake', 'Midspin Clack': 'midspin', 'Fire Midspin': 'adofai_fire',
    'Ice Midspin': 'adofai_ice', 'Level Complete': 'adofaicymbal', 'Cowbell': 'cowbell',
    'Karate Man - Toss': 'karateman_throw', 'Karate Man - Offbeat Toss': 'karateman_offbeat',
    'Karate Man - Hit': 'karateman_hit', 'Karate Man - Bulb': 'karateman_bulb', 'Ook': 'ook', 'Chorus Kid': 'choruskid',
    'Widget': 'builttoscale', 'Perfect Failed': 'perfectfail', 'Skill Star': '🌟', 'Left': 'fnf_left',
    'Down': 'fnf_down', 'Up': 'fnf_up', 'Right': 'fnf_right', 'Fail': 'fnf_death', 'Crash': 'gdcrash',
    'Crash + Orbs': 'gdcrash_orbs', 'Secret Coin': 'gd_coin', 'Mana Orbs': 'gd_orbs', 'Diamond': 'gd_diamonds',
    'Quit': 'gd_quit', 'Blast Processing': 'bwomp', 'Game Over': 'undertale_crack', 'sans': 'sans_voice',
    'Megalovania': 'megalovania', 'Megalovania Note': '🦴', 'Encounter': 'undertale_encounter', 'Bark': 'toby',
    'Vanish': 'gaster', 'Lancer Splat': 'lancersplat', 'Death': 'celeste_death', 'Holy Mantle': 'isaac_mantle',
    'MOVE': 'BABA', 'RULE': 'YOU', 'DEFEAT': 'DEFEAT', 'Flip': 'vvvvvv_flip', 'Sad': 'vvvvvv_hurt',
    'Checkpoint': 'vvvvvv_checkpoint', 'Flash': 'vvvvvv_flash', 'Magic': 'terraria_star', 'Shatter': 'terraria_pot',
    'Reforge': 'terraria_reforge', 'Stellar Tune': 'terraria_guitar', 'The Axe': 'terraria_axe', 'Dash': 'celeste_dash',
    'Spring': 'celeste_spring', 'Dash Gem': 'celeste_diamond', 'Emergency Meeting': 'amogus_emergency',
    'Kill': 'amogus_kill', 'AMONG US': 'amongus', 'Among Drip': 'amongdrip', 'Amogus': 'amogus',
    'Anvil': 'minecraft_anvil', 'Note Block - Harp': 'noteblock_harp', 'Note Block - Bass': 'noteblock_bass',
    'Note Block - Snare': 'noteblock_snare', 'Note Block - Hat': 'noteblock_click',
    'Note Block - Bell': 'noteblock_bell', 'Note Block - Banjo': 'noteblock_banjo', 'Note Block - Bit': 'noteblock_bit',
    'Note Block - Chime': 'noteblock_chime', 'Note Block - Xylophone': 'noteblock_xylophone',
    'Note Block - Guitar': 'noteblock_guitar', 'Note Block - Flute': 'noteblock_flute',
    'Note Block - Pling': 'noteblock_pling'
}
SOUND_FROM_CHANNEL = 0
SOUND_FROM_SETUP = 1
RANDOM_SOUND = 2
