NOTES_OFFSET = {
    'bong': 64,
    '🔔': 88,
    '🚫': 48,
    '🤬': 83,
    'buzzer': 46,
    'airhorn': 51,
    '🎹': 66,
    'robtopphone': 66,
    '🎸': 42,
    'hoenn': 66,
    '🎺': 66,
    'obama': 66,
    'samurai': 69,
    'familyguy': 72,
    'ultrainstinct': 69,
    'morshu': 56,
    'bup': 69,
    'mariopaint_mario': 66,
    'mariopaint_luigi': 66,
    'mariopaint_star': 78,
    'mariopaint_flower': 66,
    'mariopaint_gameboy': 66,
    'mariopaint_dog': 65,
    'mariopaint_cat': 65,
    'mariopaint_swan': 66,
    'mariopaint_baby': 73,
    'mariopaint_plane': 66,
    'mariopaint_car': 66,
    'tab_sounds': 96,
    'choruskid': 66,
    'builttoscale': 72,
    'fnf_left': 66,
    'fnf_down': 52,
    'fnf_up': 66,
    'fnf_right': 66,
    'gd_quit': 69,
    'bwomp': 54,
    '🦴': 50,
    'YOU': 73,
    'terraria_guitar': 64,
    'terraria_axe': 48,
    'amogus_emergency': 58,
    'amongdrip': 48,
    'minecraft_bell': 54,
    'noteblock_harp': 66,
    'noteblock_bass': 42,
    'noteblock_bell': 78,
    'noteblock_banjo': 66,
    'noteblock_bit': 66,
    'noteblock_chime': 78,
    'noteblock_xylophone': 78,
    'noteblock_guitar': 54,
    'noteblock_flute': 78,
    'noteblock_pling': 66
}
DRUM_NOTES = {
    35: 'adofaikick',
    36: 'adofaikick',
    37: 'sidestick',
    38: 'noteblock_snare',
    39: 'rdclap',
    40: 'hammer',
    41: 'taiko_don',
    42: 'noteblock_click',
    43: 'taiko_don',
    44: 'noteblock_click',
    45: 'taiko_don',
    46: 'ride2',
    47: '🪘',
    48: '🪘',
    49: 'ride2',
    50: '🪘',
    51: 'ride2',
    52: 'ride2',
    53: 'ride2',
    54: 'shaker',
    55: 'ride2',
    56: 'cowbell',
    57: 'ride2',
    58: 'skipshot',
    59: 'ride2',
    69: 'shaker',
    70: 'shaker',
    82: 'shaker'
}
MINECRAFT1_SETUP = {
    (0, 54): 'noteblock_bass',
    'default': 'noteblock_harp'
}
NOTE_FROM_CHANNEL = 0
NOTE_FROM_SETUP = 1
