# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.formLayout = QtWidgets.QFormLayout(self.centralwidget)
        self.formLayout.setObjectName("formLayout")
        self.btn_load_file = QtWidgets.QPushButton(self.centralwidget)
        self.btn_load_file.setObjectName("btn_load_file")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.btn_load_file)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 780, 451))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.formLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 781, 451))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.channel_layout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.channel_layout.setContentsMargins(0, 0, 0, 0)
        self.channel_layout.setObjectName("channel_layout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.scrollArea)
        self.btn_convert = QtWidgets.QPushButton(self.centralwidget)
        self.btn_convert.setObjectName("btn_convert")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.SpanningRole, self.btn_convert)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.rb_channel = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_channel.setObjectName("rb_channel")
        self.verticalLayout.addWidget(self.rb_channel)
        self.rb_note = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_note.setObjectName("rb_note")
        self.verticalLayout.addWidget(self.rb_note)
        self.rb_random = QtWidgets.QRadioButton(self.centralwidget)
        self.rb_random.setObjectName("rb_random")
        self.verticalLayout.addWidget(self.rb_random)
        self.formLayout.setLayout(3, QtWidgets.QFormLayout.FieldRole, self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "30 dollar website midi converter"))
        self.btn_load_file.setText(_translate("MainWindow", "Загрузить файл"))
        self.btn_convert.setText(_translate("MainWindow", "Конвертировать"))
        self.label.setText(_translate("MainWindow", "Режим звуков"))
        self.rb_channel.setText(_translate("MainWindow", "Звук зависит от канала"))
        self.rb_note.setText(_translate("MainWindow", "Звук зависит от высоты тона"))
        self.rb_random.setText(_translate("MainWindow", "Случайный звук"))
